/**
 * generated by Xtext 2.11.0
 */
package org.xtext.example.mydsl3.fSM;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>FSM</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl3.fSM.FSM#getType <em>Type</em>}</li>
 *   <li>{@link org.xtext.example.mydsl3.fSM.FSM#getOwnedState <em>Owned State</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl3.fSM.FSMPackage#getFSM()
 * @model
 * @generated
 */
public interface FSM extends EObject
{
  /**
   * Returns the value of the '<em><b>Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Type</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' reference.
   * @see #setType(EnumerationType)
   * @see org.xtext.example.mydsl3.fSM.FSMPackage#getFSM_Type()
   * @model
   * @generated
   */
  EnumerationType getType();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl3.fSM.FSM#getType <em>Type</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' reference.
   * @see #getType()
   * @generated
   */
  void setType(EnumerationType value);

  /**
   * Returns the value of the '<em><b>Owned State</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl3.fSM.State}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Owned State</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Owned State</em>' containment reference list.
   * @see org.xtext.example.mydsl3.fSM.FSMPackage#getFSM_OwnedState()
   * @model containment="true"
   * @generated
   */
  EList<State> getOwnedState();

} // FSM
