/**
 * generated by Xtext 2.11.0
 */
package org.xtext.example.mydsl3.fSM;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl3.fSM.Model#getTypes <em>Types</em>}</li>
 *   <li>{@link org.xtext.example.mydsl3.fSM.Model#getFsm <em>Fsm</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl3.fSM.FSMPackage#getModel()
 * @model
 * @generated
 */
public interface Model extends EObject
{
  /**
   * Returns the value of the '<em><b>Types</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl3.fSM.EnumerationType}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Types</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Types</em>' containment reference list.
   * @see org.xtext.example.mydsl3.fSM.FSMPackage#getModel_Types()
   * @model containment="true"
   * @generated
   */
  EList<EnumerationType> getTypes();

  /**
   * Returns the value of the '<em><b>Fsm</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl3.fSM.FSM}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Fsm</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Fsm</em>' containment reference list.
   * @see org.xtext.example.mydsl3.fSM.FSMPackage#getModel_Fsm()
   * @model containment="true"
   * @generated
   */
  EList<FSM> getFsm();

} // Model
