/*
 * generated by Xtext 2.11.0
 */
package org.xtext.example.mydsl3.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.example.mydsl3.ui.internal.Mydsl3Activator;

public class FSMUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return Mydsl3Activator.getInstance().getInjector("org.xtext.example.mydsl3.FSM");
	}

}
