/**
 * generated by Xtext 2.11.0
 */
package org.xtext.example.mydsl3.fSM.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.example.mydsl3.fSM.EnumerationType;
import org.xtext.example.mydsl3.fSM.FSM;
import org.xtext.example.mydsl3.fSM.FSMPackage;
import org.xtext.example.mydsl3.fSM.Model;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl3.fSM.impl.ModelImpl#getTypes <em>Types</em>}</li>
 *   <li>{@link org.xtext.example.mydsl3.fSM.impl.ModelImpl#getFsm <em>Fsm</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ModelImpl extends MinimalEObjectImpl.Container implements Model
{
  /**
   * The cached value of the '{@link #getTypes() <em>Types</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTypes()
   * @generated
   * @ordered
   */
  protected EList<EnumerationType> types;

  /**
   * The cached value of the '{@link #getFsm() <em>Fsm</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFsm()
   * @generated
   * @ordered
   */
  protected EList<FSM> fsm;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ModelImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return FSMPackage.Literals.MODEL;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<EnumerationType> getTypes()
  {
    if (types == null)
    {
      types = new EObjectContainmentEList<EnumerationType>(EnumerationType.class, this, FSMPackage.MODEL__TYPES);
    }
    return types;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<FSM> getFsm()
  {
    if (fsm == null)
    {
      fsm = new EObjectContainmentEList<FSM>(FSM.class, this, FSMPackage.MODEL__FSM);
    }
    return fsm;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case FSMPackage.MODEL__TYPES:
        return ((InternalEList<?>)getTypes()).basicRemove(otherEnd, msgs);
      case FSMPackage.MODEL__FSM:
        return ((InternalEList<?>)getFsm()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case FSMPackage.MODEL__TYPES:
        return getTypes();
      case FSMPackage.MODEL__FSM:
        return getFsm();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case FSMPackage.MODEL__TYPES:
        getTypes().clear();
        getTypes().addAll((Collection<? extends EnumerationType>)newValue);
        return;
      case FSMPackage.MODEL__FSM:
        getFsm().clear();
        getFsm().addAll((Collection<? extends FSM>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case FSMPackage.MODEL__TYPES:
        getTypes().clear();
        return;
      case FSMPackage.MODEL__FSM:
        getFsm().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case FSMPackage.MODEL__TYPES:
        return types != null && !types.isEmpty();
      case FSMPackage.MODEL__FSM:
        return fsm != null && !fsm.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //ModelImpl
