/*
 * generated by Xtext 2.11.0
 */
package org.xtext.example.mydsl3.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractFSMScopeProvider extends DelegatingScopeProvider {
}
