/*
 * generated by Xtext 2.11.0
 */
package org.xtext.example.mydsl3


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class FSMStandaloneSetup extends FSMStandaloneSetupGenerated {

	def static void doSetup() {
		new FSMStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
